### ISSUE TITLE
[plugin-publish] Request to publish a new plugin 'oss'

### ISSUE THREAD

**Issue by mailtokun** [IBM-Cloud/ibm-cloud-cli-sdk#331]
```
- name: oss
  description: Toolings of IBM Cloud Operations Support System
  company: IBM
  authors:
  - name: Kun Yang
    contact: ykunyk@cn.ibm.com
  homepage: https://github.ibm.com/cloud-sre/ibmcloud-oss-cli
  version: 0.2.36
  binaries:
  - platform: osx
    url: https://github.ibm.com/cloud-sre/ibmcloud-oss-cli/releases/download/v0.2.36/oss-darwin-amd64.zip
    checksum: 7e8f83d4e5f1a16be6235a2fb21180282a224390d4899f7ef5bd083638eef57c30be32f403fec787e081cacdf5ddbd5d32f7fbfcd78dd37b6635c3ad92bc440b
  - platform: win64
    url: https://github.ibm.com/cloud-sre/ibmcloud-oss-cli/releases/download/v0.2.36/oss-windows-amd64.zip
    checksum: d5776b854aeaef990b4024e1d2a66a07519e127638b6f49284602be7b00f3fc11356151629128e2fad35abe6030f0e9d5686fba078928b5ebb2cb1bdc5df499f
  - platform: linux64
    url: https://github.ibm.com/cloud-sre/ibmcloud-oss-cli/releases/download/v0.2.36/oss-linux-amd64.zip
    checksum: b3d6a5b938ac8f381239ca418bc0e8290806801babb7f840eba7254e25f63e1dac59a08e4498500bd09ef5df3f81d8757df4b98bcc092c91df75494b7591d609
```
